platform :ios, '9.0'

#use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
workspace 'TVProjectionDemo2'
target 'TVProjectionDemo2'

pod 'AFNetworking'
pod 'LookinServer'
pod 'DZNEmptyDataSet'
pod 'CocoaAsyncSocket'
pod 'IGListKit'


pre_install do |installer|
#    puts '------  start check af-uiwebV  ------'
    dir_af = File.join(installer.sandbox.pod_dir('AFNetworking'), 'UIKit+AFNetworking')
    Dir.foreach(dir_af) {|x|
      real_path = File.join(dir_af, x)
      if (!File.directory?(real_path) && File.exists?(real_path))
        if((x.start_with?('UIWebV') || x == 'UIKit+AFNetworking.h'))
          File.delete(real_path)
          puts 'delete:'+ x
        end
      end
    }
#    puts '----- end check ------'
end
